_wandb:
    value:
        cli_version: 0.25.1
        e:
            xcl8w6qcu2zkj4nb2znmj15dhsqalrcg:
                args:
                    - --vla_checkpoint_path
                    - runs/ckpts/mme_vla_suite/perceptual-framesamp-modul/79999/params
                    - --dataset_path
                    - data/robomme_preprocessed_data
                    - --exp_name
                    - rl_selector_v2
                    - --batch_size
                    - "64"
                    - --wandb_enabled
                    - --tasks
                    - PatternLock
                    - RouteStick
                codePath: scripts/train_selector_v2.py
                codePathLocal: scripts/train_selector_v2.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "233904164864"
                        used: "41375395840"
                email: shaunak.halbe@gmail.com
                executable: /coc/testnvme/shalbe3/miniconda/envs/robomme/bin/python
                git:
                    commit: c457ea2f13c8994a308be0c4401c1e7489e3887e
                    remote: https://github.com/RoboMME/robomme_policy_learning.git
                gpu: NVIDIA A40
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-4d4432ce-c2cd-5364-e184-b901422152bb
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-a6ad8b4d-5ca6-fa40-330b-9541237789f0
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-ea8d9c47-c31b-3870-5dae-ab2bd3f5a589
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-cac5c09e-4afd-e7a7-db91-2fb294a03ab5
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-3dcf394e-5cd0-185c-f3c1-484e1bedd9e6
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-851ed0ab-fdc1-9993-0f50-65f94f032d6a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-fd3b2373-8bf2-7c1c-7661-497d276176b2
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-bded548a-dba8-01c5-e659-9aa485735ef9
                host: dave.cc.gatech.edu
                memory:
                    total: "540840906752"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.39
                program: /nethome/shalbe3/robomme_policy_learning/scripts/train_selector_v2.py
                python: CPython 3.11.15
                root: /nethome/shalbe3/robomme_policy_learning
                slurm:
                    cluster_name: skynet
                    conf: /opt/slurm/configs/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00FFFFFF00FFFFFF00FFFFFF00FFFFFF
                    cpu_bind_list: 0x00FFFFFF00FFFFFF00FFFFFF00FFFFFF
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "96"
                    cpus_per_gpu: "12"
                    distribution: cyclic
                    gpus_on_node: "8"
                    gpus_per_node: a40:8
                    gtids: "0"
                    job_account: kira-lab
                    job_cpus_per_node: "96"
                    job_end_time: "1777412583"
                    job_gid: "2626"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "2920026"
                    job_name: train_selector_v2
                    job_nodelist: dave
                    job_num_nodes: "1"
                    job_partition: kira-lab
                    job_qos: long
                    job_start_time: "1776807783"
                    job_uid: "3173960"
                    job_user: shalbe3
                    jobid: "2920026"
                    launch_node_ipaddr: 127.0.0.1
                    localid: "0"
                    mem_per_node: "262144"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dave
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 127.0.0.1
                    srun_comm_port: "7646"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "7646"
                    step_nodelist: dave
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /nethome/shalbe3/robomme_policy_learning
                    submit_host: sky2.cc.gatech.edu
                    task_pid: "1992570"
                    tasks_per_node: "1"
                    topology_addr: dave
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2026-04-21T21:43:38.678388Z"
                writerId: xcl8w6qcu2zkj4nb2znmj15dhsqalrcg
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 71
                - 105
            "2":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 71
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.15
            "5": 0.25.1
            "6": 4.57.3
            "8":
                - 2
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 64
candidate_emb_dim:
    value: 2048
clip_epsilon:
    value: 0.2
dataset_path:
    value: data/robomme_preprocessed_data
entropy_coef:
    value: 0.01
eval_interval:
    value: 2000
exp_name:
    value: rl_selector_v2
front_view_emb_dim:
    value: 2048
gamma:
    value: 0
history_config:
    value: perceptual-rlselector-modul.yaml
instruction_emb_dim:
    value: 256
log_interval:
    value: 10
lr:
    value: 0.0003
max_candidates:
    value: 512
max_grad_norm:
    value: 1
neighbor_suppression_radius:
    value: 0
num_frames_to_select:
    value: 32
num_train_steps:
    value: 1512
num_views:
    value: 1
ppo_epochs:
    value: 4
ppo_minibatch_size:
    value: 16
proprio_dim:
    value: 8
query_dim:
    value: 256
redundancy_penalty_coef:
    value: 0.01
redundancy_time_threshold:
    value: 2
save_interval:
    value: 302
scorer_hidden_dim:
    value: 256
selector_checkpoint_dir:
    value: runs/ckpts/rl_selector
stage2_unfreeze_action_expert_lora:
    value: false
stage2_unfreeze_modulation:
    value: false
token_budget:
    value: 512
token_per_image:
    value: 16
use_episode_progress:
    value: true
value_loss_coef:
    value: 0.5
vla_checkpoint_path:
    value: runs/ckpts/mme_vla_suite/perceptual-framesamp-modul/79999/params
wandb_enabled:
    value: true
wandb_project:
    value: rl-frame-selector
